openapi: 3.0.0
info:
  title: Environmental Data API
  version: 1.0.2
servers:
  - url: http://127.0.0.1:8080/HealthAndAir/v2
paths:
  /secondaryData/AqiOneDay:
    get:
      summary: Get AQI data for the current day
      operationId: controller.get_one_day_data_aqi
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AqiMeasurement'
  /secondaryData/AqiOneWeek:
    get:
      summary: Get AQI data for the past week
      operationId: controller.get_one_week_data_aqi
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AqiMeasurement'
  /secondaryData/KidbrightOneDay:
    get:
      summary: Get Kidbright data for the current day
      operationId: controller.get_one_day_data_kidbright
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightMeasurement'
  /secondaryData/KidbrightOneWeek:
    get:
      summary: Get Kidbright data for the past week
      operationId: controller.get_one_week_data_kidbright
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KidbrightMeasurement'
  /secondaryData/TmdOneDay:
    get:
      summary: Get TMD data for the current day
      operationId: controller.get_one_day_data_tmd
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TmdMeasurement'
  /secondaryData/TmdOneWeek:
    get:
      summary: Get TMD data for the past week
      operationId: controller.get_one_week_data_tmd
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TmdMeasurement'
components:
  schemas:
    AqiMeasurement:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
          nullable: true
        humidity:
          type: number
          nullable: true
        latitude:
          type: number
          nullable: true
        longitude:
          type: number
          nullable: true
        timestamp:
          type: string
          format: date-time
        source:
          type: string
      required:
        - id
        - timestamp
        - source
    KidbrightMeasurement:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
          nullable: true
        heartbeat_bpm:
          type: number
          nullable: true
        humidity:
          type: number
          nullable: true
        dew:
          type: number
          nullable: true
        pressure:
          type: number
          nullable: true
        wind:
          type: number
          nullable: true
        wind_gust:
          type: number
          nullable: true
        light:
          type: number
          nullable: true
        latitude:
          type: number
          nullable: true
        longitude:
          type: number
          nullable: true
        timestamp:
          type: string
          format: date-time
        source:
          type: string
      required:
        - id
        - timestamp
        - source
    TmdMeasurement:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
          nullable: true
        humidity:
          type: number
          nullable: true
        dew:
          type: number
          nullable: true
        pressure:
          type: number
          nullable: true
        wind:
          type: number
          nullable: true
        wind_gust:
          type: number
          nullable: true
        latitude:
          type: number
          nullable: true
        longitude:
          type: number
          nullable: true
        timestamp:
          type: string
          format: date-time
        source:
          type: string
      required:
        - id
        - timestamp
        - source