openapi: 3.0.0
info:
  title: Health Data API
  version: 1.0.2
servers:
  - url: http://127.0.0.1:8080/rain-api/v2

paths:
  /secondaryData/OneHour:
    get:
      summary: Get all entries from the past hour
      operationId: controller.get_one_hour_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'

  /secondaryData/OneDay:
    get:
      summary: Get all entries from today
      operationId: controller.get_one_day_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Measurement'

components:
  schemas:
    Measurement:
      type: object
      properties:
        id: { type: integer }
        temperature: { type: number }
        heartbeat_bpm: { type: string, nullable: true }
        humidity: { type: number }
        aqi: { type: number, nullable: true }
        pm25: { type: number, nullable: true }
        pm10: { type: number, nullable: true }
        o3: { type: number, nullable: true }
        no2: { type: number, nullable: true }
        co: { type: number, nullable: true }
        so2: { type: number, nullable: true }
        dew: { type: number, nullable: true }
        pressure: { type: number, nullable: true }
        wind: { type: number, nullable: true }
        wind_gust: { type: number, nullable: true }
        dominentpol: { type: string, nullable: true }
        light: { type: number }
        latitude: { type: number }
        longitude: { type: number }
        timestamp: { type: string, format: date-time }
        source: { type: string }